<?php
/**
 *
 * @file user-log-in.php
 *
 *
 * @description This is the default user login template.
 *
 * Do not edit this file. Create your own template file in theme folder.
 *
 * @warning Do not edit this file unless you know what you are doing.
 *
 *
 *
 *
 *
 *
 */
?>
<script>
    jQuery( function( $ ) {
        var $log_in_form = $('section.log-in form');
        $log_in_form.submit ( function (e) {
            e.preventDefault();
            on_submit();
            var $form = $(this);
            var url = $form.prop('action') + '?' + $form.serialize();
            console.log(url);
            $.post(url, function(re) {
                on_result(re);
            });
        });
        function on_submit() {
            $log_in_form.find('.line.spinner').show();
            $log_in_form.find('.line.submit').hide();
            $log_in_form.find('.line.error').hide();
        }
        function on_result(re) {
            var $error = $('.line.error');
            setTimeout(function(){
                $('.line.spinner').hide();
                if ( re['code'] ) {
                    $('.line.submit').show();
                    $error.html( '<i class="fa fa-exclamation-triangle"></i> ' + re['message'] );
                    $error.show();
                }
                else if ( typeof re['code'] == 'undefined' ) {
                    $('.line.submit').show();
                    $error.html( '<i class="fa fa-exclamation-triangle"></i> Server Internal Error ...');
                    $error.show();
                }
                else {
                    location.href = home_url;
                }
            }, 500);
        }

    });
</script>
<h2>Plugin Page/Login</h2>
<?php if ( in('action') == 'lostpassword' ) { ?>
    <?php _e('Password reset link has been sent to your email.') ?>
<?php } ?>
<section class="log-in">
    <form action="<?php echo home_url('/user/loginSubmit')?>" method="POST">

        <?php wp_nonce_field('log-in'); ?>

        <fieldset class="form-group">
            <label class="caption" for="user_login">User ID</label>
            <div class="text"><input type="text" name="user_login" maxlength="64" id="user_login" tabindex="100"></div>
        </fieldset>

        <fieldset class="form-group">
            <label class="caption" for="user_pass">Password</label>
            <div class="text"><input type="password" name="user_pass" maxlength="64" id="user_pass" tabindex="101"></div>
        </fieldset>

        <fieldset class="form-group">
            <div class="text"><input type="checkbox" name="rememberme" id="rememberme" tabindex="101"></div>
            <label class="caption" for="rememberme">Keep me logged in</label>
        </fieldset>


        <div class="line spinner" style="display:none;">
            <i class="fa fa-spinner fa-spin"></i> Connecting to server ...
        </div>

        <div class="line error" style="display:none;"></div>

        <input class="btn btn-primary" type="submit" value="Log In" tabindex="121">

    </form>


    <div class="lost-password-button">
        <a href="<?php echo home_url('/user-password-lost')?>">Lost Password?</a>
    </div>

    <a href="<?php echo home_url('/user-register')?>">Register</a>
</section>
